### PR TITLE
Datefilename

### LINKED ISSUE #109: 2021-02-06-somepost.md style filenames date parsing
I name blog post files in this style: `2021-02-06-somepost.md`. Could there be a processor that takes the date from filenames like this? Or is there one already perhaps? And then remove the date from the url slug of course ;)

Thanks!

### PR DESCRIPTION
**Pull request by brenthuisman**
Adds processor that processes filename 2014-05-06-name.md to path /name.html and sets page.Date to 2014-05-06.

Fixes #109

### CODE REVIEW

**Comment by piranha** [comment]
As an idea I like that! As for implementation, don't you think matching whole date with a single regexp makes more sense? Like `(\d{4}-\d{2}-\d{2})-(.*)`, so there is no subsequent string concatenation.

**Comment by brenthuisman** [comment]
Sure!

**Comment by piranha** [comment]
Hmm... It's a bit stupid that I did not write that together with a first comment, but do you mind updating `README.md`? It's the only real documentation the project has. 😁

**Comment by brenthuisman** [comment]
No worries mate, here you go!

**Comment by piranha** [comment]
[2.27](https://github.com/piranha/gostatic/releases/tag/2.27) is out with this change.

**Pull request merged**
