### PR TITLE
Added yaml and jekyllify processors.

### PR DESCRIPTION
**Pull request by Juev**
New processors for processing jekyll sites.
Added doc stings for new functions.
Fix Page.Collect, used source across destination.
Added UPX for make.

### CODE REVIEW

**Comment by Juev** [comment]
I have not updated the readme file, if required, let me know.

**Comment by piranha** [comment]
Yeah, adding documentation is good, because in other case it's really hard to discover. :-)

**Comment by Juev** [comment]
Updated.
I think this update affects #65 and #83 issues.

**Comment by piranha** [comment]
Thanks!

**Pull request merged**
