### PR TITLE
Add alphabetize_pages function

### PR DESCRIPTION
**Pull request by akerl**
I'm using gostatic to build a simple site that lists content. Because of this, I wanted to be able to alphabetize the group of pages for display in the index.

I'm not sold on the function name, and also realize this may not be a good fit for the more common blog-based usage of gostatic, but figured I'd send in a PR in case it's useful to other folks.

### CODE REVIEW

**Comment by piranha** [comment]
Yeah, the name was a little confusing to me, I thought it's about generating alphabet of pages. :-)

What do you think about `pagesort` or `abcsort`?

**Comment by akerl** [comment]
Updated to be `abcsort`. I intentionally didn’t go for a more general name like pagesort given that I assume sorting alphabetically isn’t the thing most people would expect when sorting posts, so I wanted to have the name clarify the type of sort.

**Comment by piranha** [comment]
Sorry didn't write this in the first comment, but would you care to update `README.md`? :)

**Comment by akerl** [comment]
Added!

**Comment by piranha** [comment]
Thanks, I've released version 2.35 with this change.

**Pull request merged**
